version: "3.0"
services:
  scm:
    image: scmmanager/scm-manager:2.25.0
    ports:
      - "8080:8080"
    volumes:
      - scm_data:/var/lib/scm
    environment:
      JAVA_OPTS: ${JAVA_OPTS}
volumes:
  scm_data: {}
