version: '2.0'
services:
  scm:
    image: scmmanager/scm-manager:2.25.0
    ports:
      - "8080:8080"
      # if the ssh plugin is used
      - "2222:2222"
    volumes:
      - scmhome:/var/lib/scm
volumes:
  scmhome: {}
